<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>bb9e6b00-7c45-4ffd-91d6-98b1177930b1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazor-ApexCharts" Version="*" />
    <PackageReference Include="Microsoft.Identity.Client" Version="*" />
    <PackageReference Include="MudBlazor" Version="*" />
  </ItemGroup>

</Project>
